language: python

python:
    # - "2.6"
    - "2.7"
    # - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

install:
  - pip install numpy
  - pip install pandas pytest requests
  - pip install ordereddict cchardet argparse chardet
  - pip install openpyxl==2.0.3
  - python setup.py install

script:
    - travis_wait py.test

notifications:
  email:
    recipients:
      - kinverarity@hotmail.com
    on_success: change
    on_failure: change
